### ISSUE TITLE
assistance

### ISSUE THREAD

**Issue by 1029734570** [tongnie/ImputeFormer#3]
Could you please provide the code for this fill-in visualization?

**Comment by tongnie** [comment]
Sorry for the late reply! I have uploaded a simple visualization function in this notebook [Imputation_Viz.ipynb](https://github.com/tongnie/ImputeFormer/blob/main/Imputation_Viz.ipynb).

You can use this function to plot a single series, then merge all the subfigures.

Hope this is helpful for you!

**Comment by 1029734570** [comment]
Thank you, Tongnie. This has been extremely helpful for me.
